### ISSUE TITLE
Changes not detected properly

### ISSUE THREAD

**Issue by AuspeXeu** [anders94/blockchain-demo#1]
In your demo under the "Tokens" section, I can change the first row of each Tx: segment without invalidating the hash. I don't think this is how it is intended, right?

**Comment by viebel** [comment]
I have also encountered this bug

**Comment by mattmazzola** [comment]
It looks like it was already fixed in this commit:
https://github.com/anders94/blockchain-demo/commit/edb64f62f08d61cde5fa08470cb8c1a97e8e92f3#diff-9dc8bb4e5060ce113f97d3aa444b7ebbR44

Which changes start index to 0 instead of 1 to include first transaction.

However, the published website is not updated with the bug fix.  The tokens.jade is still starting at 1

**Comment by anders94** [comment]
Right, that's exactly what happened. I have updated my site to the latest version.
