### ISSUE TITLE
Enhancement in Blockchain section

### ISSUE THREAD

**Issue by KushalGH** [anders94/blockchain-demo#58]
HI Ander, 

your project is awesome. While playing around, the Blockchain section, I found some issue.

If I mine all the blocks, like block 1, Block 2, Block 3 and Block 4.

If I change something in Block 1, my complete chain gets invalidated, that's correct. Now, I directly goes to Block 3, and mine it. It's getting mined. This should not happen. 

This breaks the functionality of Blockchain.

**Comment by anders94** [comment]
I would argue that functionality is correct. You can have a valid block built after an invalid one. The entire chain is not valid though because not all blocks are considered valid. You can't just check the validity of the last block, you have to make sure all blocks "are green" to confirm that the entire chain follows the rules.
