### ISSUE TITLE
Broken url

### ISSUE THREAD

**Issue by DaWe35** [anders94/blockchain-demo#70]
At the bottom of the index page, the 'by Anders Brownworth' --> andersbrownworth.com URL has broken. Later I can create a pl if you want.

_Off: if you see fantasy in it, I can re-design a bit the page to make it more modern and handy. Would you like me to deal with it?_

**Comment by anders94** [comment]
Hey, thanks for the comment and sorry about the slow reply. I don't see that as broken. (it is possible it was fixed in a recent update though)

And thanks for the redesign offer. I'm sticking to fairly standard Bootstrap template look and feel but if you want to submit a PR (screenshots please!) I would look at it.
